### ISSUE TITLE
Explain what the crate does in the README

### ISSUE THREAD

**Issue by Aloso** [x-hgg-x/tz-rs#1]
For people who are not familiar with the POSIX localtime, gmtime and mktime functions.

**Comment by extrawurst** [comment]
also the context of it with chrono, time-rs and the whole unsoundness that spawned this :)

**Comment by x-hgg-x** [comment]
Fixed in [f919657](https://github.com/x-hgg-x/tz-rs/commit/f919657f6e769ae8b987366d4c32609b41409658).
