### ISSUE TITLE
Replace `Arc<str>`|`&'static str` by TinyStr8

### ISSUE THREAD

**Issue by Kijewski** [x-hgg-x/tz-rs#18]
There is no need to use a dynamically allocated `Arc<str>` (yes, I realize that using this type was my idea) when all time zone designations are 5 or fewer ASCII characters. You could remove the `Arc<str>`|`&'static str` schism by using e.g. [tinystr::TinyAsciiStr<8>].

[tinystr::TinyAsciiStr<8>]: https://docs.rs/tinystr/0.5.0/tinystr/struct.TinyAsciiStr.html

**Comment by x-hgg-x** [comment]
Fixed in [80036c5](https://github.com/x-hgg-x/tz-rs/commit/80036c52371ab4edb81143731f161a5d1ea130e1).
