### ISSUE TITLE
Consider reverting "Simplify DateTime api"

### ISSUE THREAD

**Issue by Kijewski** [x-hgg-x/tz-rs#9]
In many cases I (and I guess many other users, too), operate on UNIX timestamps, only converting the ts some local time zone to present the date to a user. It's useful to have a tinier UTC-only type for this use case. So at least in my opinion the API was better before 7e38724f66fed3b370e8a5763a3fca15ef56f000.

**Comment by x-hgg-x** [comment]
Fixed in [2cf0a22](https://github.com/x-hgg-x/tz-rs/commit/2cf0a225096c8ffb6ba6da3d615abbb94fa1be15).
